### ISSUE TITLE
I was directly used the docker image, but not find the idp-config.json 

### ISSUE THREAD

**Issue by robertbob987** [walt-id/waltid-idpkit#20]
I was directly used the docker image, but not find the idp-config.json
docker pull waltid/idpkit
docker run -p 8080:8080 -e WALTID_DATA_ROOT=/data -v $PWD:/data waltid/idpkit run
docker exec -it 4b /bin/bash
root@4b4a9b59736e:/waltid-idpkit# ls
bin data lib service-matrix.properties signatory.conf

**Comment by robertbob987** [comment]
root@iotg-monitore-server-a2c3:~# docker container ls
CONTAINER ID   IMAGE              COMMAND                  CREATED          STATUS          PORTS                                       NAMES
df690b990d72   waltid/walletkit   "/waltid-walletkit/b…"   5 minutes ago    Up 5 minutes    0.0.0.0:8082->8082/tcp, :::8082->8082/tcp   elastic_booth
62429b05c162   waltid/idpkit      "/waltid-idpkit/bin/…"   13 minutes ago   Up 13 minutes   0.0.0.0:8081->8081/tcp, :::8081->8081/tcp   peaceful_clarke
root@iotg-monitore-server-a2c3:~# docker exec -it 62 /bin/sh
# su root
root@62429b05c162:/waltid-idpkit# ls
bin  data  lib	service-matrix.properties  signatory.conf
root@62429b05c162:/waltid-idpkit# cd data
root@62429b05c162:/waltid-idpkit/data# ls
did  ebsi  key	vc
root@62429b05c162:/waltid-idpkit/data# cd ..
root@62429b05c162:/waltid-idpkit# ls
bin  data  lib	service-matrix.properties  signatory.conf
root@62429b05c162:/waltid-idpkit# cd ..
root@62429b05c162:/# ls
bin  boot  data  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var  waltid-idpkit
root@62429b05c162:/# cd data
root@62429b05c162:/data# ls
CloudResetPwdUpdateAgent  bin	data  etc   initrd.img	    lib    lost+found  mnt  proc  run	snap  swapfile	tmp  var      vmlinuz.old
CloudrResetPwdAgent	  boot	dev   home  initrd.img.old  lib64  media       opt  root  sbin	srv   sys	usr  vmlinuz
root@62429b05c162:/data#

**Comment by mikeplotean** [comment]
Answered at https://github.com/walt-id/waltid-ssikit/issues/169
